scalar BigInt
scalar DateTime

type User {
  id: ID!
  given_name: String
  username: String!
  name: String!
  description: String
  image: String
  banner: String
  provider_picture: String
  gender: String
  email: String!
  created_at: DateTime
  last_login: DateTime
}

type Topic {
  name: String!
  label: String!
}
