mutation createRootGroup($owner: String!, $name: String!, $slug: String!) {
  insert_groups(
    objects: { name: $name, path: $slug, owner_id: $owner }
  ) {
    returning {
      id
      path
      name
      type
      is_public
      is_accessible
      created_at
      chat_settings {
        is_public
      }
      members {
        user_id
        name
      }
    }
  }
}

"""
{
  "owner": "test-1",
  "name": "Test Group",
  "slug": "test"
}
"""
