mutation createRootGroup($name: String!, $path: String!, $user: String!) {
  insert_groups(
    objects: {
      profile: { data: { name: $name } }
      path: $path
      members: { data: { user_id: $user, type: owner } }
    }
  ) {
    returning {
      id
      path
      is_accessible
      type
      created_at
      chat_settings {
        is_public
      }
      profile {
        name
        is_public
      }
    }
  }
}
