mutation createUser(
  $id: String!
  $email: String!
  $username: String!
  $name: String!
  $profileImage: String
) {
  insert_users(
    objects: {
      id: $id
      email: $email
      username: $username
      personal_space: {
        data: {
          path: $username
          type: user
          profile: { data: { name: $name, image: $profileImage } }
        }
      }
    }
  ) {
    returning {
      id
      email
      username
      created_at
      personal_space {
        path
        profile {
          name
          image
          is_public
        }
        members {
          user_id
          type
          joined_at
        }
      }
    }
  }
}

# {
#   "id": "test-1",
#   "email": "user1@test.com",
#   "username": "UserTest",
#   "name": "Usuario de prueba"
# }
