mutation createRootGroup($owner: String!, $name: String!, $slug: String!, $description: String) {
  insert_groups(
    objects: { name: $name, path: $slug, description: $description, owner_id: $owner }
  ) {
    returning {
      id
      path
      name
      description
      image
      banner
      is_public
      is_accessible
      created_at
    }
  }
}
