mutation createSubgroup($owner: String!, $name: String!, $slug: String!, $parent: Int!) {
  insert_groups(
    objects: {
      profile: { data: { name: $name } }
      path: $slug
      parent_id: $parent
      members: { data: { username: $owner, role: owner } }
    }
  ) {
    returning {
      id
      path
      parent_id
      is_accessible
      type
      created_at
      chat_settings {
        is_public
      }
      profile {
        name
        is_public
      }
      root {
        path
        profile {
          name
        }
      }
      parent {
        path
        profile {
          name
        }
      }
    }
  }
}
