mutation createSubgroup($owner: String!, $name: String!, $slug: String!, $parent: bigint!) {
  insert_groups(objects: { name: $name, path: $slug, parent_id: $parent, owner_id: $owner }) {
    returning {
      id
      path
      parent_id
      name
      is_public
      is_accessible
      type
      created_at
      chat_settings {
        is_public
      }
      root {
        path
        name
      }
      parent {
        path
        name
      }
    }
  }
}

"""
{
  "owner": "test-1",
  "name": "Test Subgroup",
  "slug": "subgroup",
  "parent": 84109545630073942
}
"""
