mutation createUser($id: String!, $email: String!, $name: String!, $username: String!) {
  insert_users(
    objects: {
      id: $id
      email: $email
      personal_space: { data: { path: $username, type: user, name: $name, owner_id: $id } }
    }
  ) {
    returning {
      id
      created_at
      personal_space {
        username: path
      }
      main_profile {
        name
        description
        image
        banner
      }
    }
  }
}

"""
{
  "id": "test-1",
  "email": "user1@test.com",
  "username": "UserTest",
  "name": "Usuario de prueba"
}
"""
