query getUser($username: String!) {
  groups(where: { path: { _eq: $username }, type: { _eq: user } }) {
    path
    is_public
    owner {
      provider_picture
      created_at
      main_profile {
        name
        description
        image
        banner
      }
    }
  }
}
