mutation joinGroup($user: String!, $group: bigint!) {
  insert_members(objects: { user_id: $user, group_id: $group }) {
    returning {
      name
      role
      joined_at
      group {
        path
        name
      }
    }
  }
}

"""
{
  "user": "test-2",
  "group": 85531844811949080
}
"""
