mutation joinGroup($group: Int!, $user: String!) {
  insert_members(objects: { group_id: $group, user_id: $user }) {
    returning {
      name
      role
      joined_at
      group {
        path
        name
      }
    }
  }
}
