mutation updateLastLogin($id: String!, $lastLogin: timestamptz!) {
  update_users(where: { id: { _eq: $id } }, _set: { last_login: $lastLogin }) {
    returning {
      id
      created_at
      last_login
      given_name
      provider_picture
      gender
      personal_space {
        username: path
      }
      main_profile {
        name
        description
        image
        banner
      }
    }
  }
}
